### PR TITLE
Problem Loading IPFS node using js lib

### PR DESCRIPTION
**Pull request by ckartik**
## Issue
Running into an issue trying to get a basic IPFS node running through the IPFS-js library.
@DougAnderson444 Let me know if you've got any idea why this might be happening.

### Stack-Trace
```bash
a/HydroFile/example/jsonld/mvp.js:4
const ipfs = await IPFS.create()
             ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1022:15)
    at Module._compile (node:internal/modules/cjs/loader:1056:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

### CODE REVIEW

**Comment by ckartik** [comment]
Seems the file: `.../HydroFile/example/jsonld/node_modules/ipfs-core/src/components/index.js`
Is exporting a promise, so we should be able to wait on it, very weird.
```javascript
static async create (options = {}) { // Line 197
   ...
```

**Comment by ckartik** [comment]
Turns out I didn't understand the event loop. Node doesn't allow you to .Wait() on a thread because of it's single threaded/event loop architecture. Had to use a callback since I was using `ipfs` inside a script.

**Comment by DougAnderson444** [comment]
Yes I see you figured that out. I've added a bit to this branch to make it a bit more standard to the way people write node code, and pushed the changes.

Just so you know, this is great comments for an issue, whereas the pull requests are when you want to merge new code into existing code.

**Comment by ckartik** [comment]
Thanks! I'll def need a look over on my PRs. 

Cool, yeah I was torn between the two, I'll post in issues if I run into something again.

**Pull request closed without merging**
